//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoData
    {
        public int recordID { get; set; }
        public string description { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public System.DateTime time { get; set; }
        public string remarks { get; set; }
    }
}
